honeypotio/searchspot

src/lib.rs.in, src/matches.rs, src/resources/talent.rs
=> Implement full text search for work_roles

.travis.yml, src/resources/talent.rs
=> Previous job titles

Cargo.lock, src/resources/talent.rs
Solve warnings about sorting fields with missing unmapped types.
=> Add unmapped type to sorting fields

Cargo.lock, Cargo.toml, README.md, src/resource.rs, src/resources/talent.rs, src/server.rs
=> Bulk indexing

README.md, app.json, src/resources/talent.rs
This PR introduces a very basic support to the pagination when the query parameters `offset` and `per_page` are given.
=> Pagination

src/resources/talent.rs
Basically, we were using the number of results returned by
ElasticSearch as `total`.
The problem is, we filter said results to ignore the ones which
have a score less than 0.55.
With this PR we set `total` to the actual number of results using
`Array::len`.
=> resources/talent: fix total when results are empty

src/resources/talent.rs
Bookmarks should work when more than X bookmarks present
https://github.com/honeypotio/honeypot/pull/615
=> [bugfix] remove min score and score tracking from non keywoard search

Cargo.lock, Cargo.toml
In the next PR we'll have to implement some proper printing of the errors :X
=> cargo: enable SSL features

src/resources/talent.rs
Implement our new implementation of `Talent`'s `SalaryExpectations`.
=> resources/talent: add new salary_expectations model

.travis.yml, Cargo.toml, examples/default.toml, src/config.rs, src/lib.rs, src/logger.rs, src/macros.rs, src/main.rs, src/monitor.rs, src/resources/talent.rs, src/server.rs
The only problem for this PR is that it requires nightly to compile because of [this feature](https://github.com/honeypotio/searchspot/compare/master...rollbar#diff-b4aea3e418ccdb71239b96952d9cddb6R1)  ([RFC](https://github.com/Kimundi/rfcs/blob/b48ef3700842391b28fb96298d274edeb12edf6c/text/0000-conservative-impl-trait.md), unstable with the meaning that the design could change more or less drastically with newer releases).
#37
=> *: Implement error tracking through monitors

examples/default.toml, src/config.rs, src/monitor.rs, src/server.rs
read-only tokens live for 120s, write-mode tokens for 30s
=> server: set different token lifespans for reqs

Cargo.toml, app.json, examples/default.toml, src/config.rs, src/lib.rs, src/resources/talent.rs, src/server.rs
https://github.com/honeypotio/honeypot/pull/995
https://github.com/honeypotio/honeypot/issues/947
=> Update searchspot to reflect Fe integration

src/resources/talent.rs
=> As a recruiter I can filter talents that are new this week [#1235]

Cargo.toml, src/config.rs, src/lib.rs, src/resource.rs, src/resources/talent.rs
As serde went to stable, let's upgrade it together to some of the other crates we are using.
Lots of hugs 🐼
=> Upgrade serde (1.0), rs-es, chrono and toml

Cargo.toml, src/resources/mod.rs, src/resources/talent.rs, src/server.rs
https://github.com/honeypotio/honeypot/issues/1437
=>  Make Language Filters More Accurate for Recruiters #1437

src/resources/talent.rs
When a `job_id` is given, we ask ES to not sort and/or paginate results since we'll do that manually.
=> resources/talent: sort talents by their score

src/resources/talent.rs
Thanks rust for being so nice.
Also include #50.
=> Use pagination when job_id is given

src/resources/score.rs, src/resources/talent.rs
Include the data for sending feedback to MindMatch.
=> MindMatch feedback

Cargo.toml, src/resources/talent.rs
As for now we're not going to using them, this PR will remove any reference to them from the talent resource.
=> Remove scores

README.md
Hopefully people won't disregard the repo as broken at a glance now :)
=> README: Show master branch build status

src/config.rs, src/lib.rs, src/logger.rs, src/macros.rs, src/main.rs, src/matches.rs, src/monitor.rs, src/resource.rs, src/resources/mod.rs, src/resources/score.rs, src/resources/talent.rs, src/server.rs, src/terms.rs
Might want to check individual commits as the `rustfmt` causes a large diff.
=> Cleanup some older code

.gitignore, Cargo.lock, app.json, src/resources/talent.rs
Allow searching by `maximum_salary`. If there are cities in the query then we ignore salaries which are not part of the set.
=> Add salary_expectations filter

Cargo.lock, Cargo.toml, src/config.rs, src/lib.rs, src/server.rs
cc https://github.com/honeypotio/honeypot/issues/2934
=> Allow configuring thread counts through the ENV

Cargo.lock, Cargo.toml, src/resources/talent.rs
Blocked by https://github.com/benashford/rs-es/issues/56 if we want to actually have proper explains
=> Add support for debugging the ES query generated
